### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by MyZik** [maxbeckers/amazon-alexa-bundle#2]
Hi. Thanks for your work.

I have problems with my endpoints. I've installed the bundle and trying to configure handlers:

**/app/config/routes/maxbeckers_amazon_alexa.yaml**
```yaml
maxbeckers_amazon_alexa:
  path: /alexa/
  defaults: { _controller: MaxBeckersAmazonAlexaBundle:AmazonAlexa:amazonRequest }
```

Here is my `app/config/services.yaml` file:

```yaml
... 

alexa.launch_request.handler:
        class: App\Intents\LaunchRequest\LaunchRequestHandler
        arguments:
            - '@maxbeckers_amazon_alexa.response_helper' # ResponseHelper
        tags:
            - 'maxbeckers_amazon_alexa.request_handler'
```

And my request handler:

```php
<?php

declare(strict_types=1);

namespace App\Intents\LaunchRequest;

use MaxBeckers\AmazonAlexa\Helper\ResponseHelper;
use MaxBeckers\AmazonAlexa\Request\Request;
use MaxBeckers\AmazonAlexa\RequestHandler\AbstractRequestHandler;
use MaxBeckers\AmazonAlexa\Response\Response;

class LaunchRequestHandler extends AbstractRequestHandler
{
    /**
     * @var ResponseHelper
     */
    private ResponseHelper $responseHelper;

    /**
     * @param ResponseHelper $responseHelper
     */
    public function __construct(ResponseHelper $responseHelper)
    {
        $this->responseHelper          = $responseHelper;
        $this->supportedApplicationIds = ['my-id'];
    }

    /**
     * @param Request $request
     * @return bool
     */
    public function supportsRequest(Request $request): bool
    {
        return $request->request instanceof Request\Standard\LaunchRequest;
    }

    /**
     * @param Request $request
     * @return Response|null
     */
    public function handleRequest(Request $request): ?Response
    {
        return $this->responseHelper->respond('Success :)');
    }
}
```

I'm testing the app with amazon developer console, and get an error:

`SKILL_ENDPOINT_ERROR: Skill returned with a non-ok status [500, Internal Server Error]` and another ones like this..

<img width="1243" alt="Bildschirmfoto 2020-09-19 um 19 32 46" src="https://user-images.githubusercontent.com/12817320/93683169-27ab9b00-faaf-11ea-8b01-49db8410289c.png">

What am I doing wrong?
